# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_incidence = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_incidence.sizePolicy().hasHeightForWidth())
        self.gb_incidence.setSizePolicy(sizePolicy)
        self.gb_incidence.setObjectName("gb_incidence")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gb_incidence)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.gb_incidence)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_incidence = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_incidence.sizePolicy().hasHeightForWidth())
        self.label_incidence.setSizePolicy(sizePolicy)
        self.label_incidence.setObjectName("label_incidence")
        self.gridLayout.addWidget(self.label_incidence, 0, 0, 1, 2)
        self.sb_incidence = QtWidgets.QDoubleSpinBox(self.widget)
        self.sb_incidence.setObjectName("sb_incidence")
        self.gridLayout.addWidget(self.sb_incidence, 1, 0, 1, 2)
        self.label_top_incidence = QtWidgets.QLabel(self.widget)
        self.label_top_incidence.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_top_incidence.setObjectName("label_top_incidence")
        self.gridLayout.addWidget(self.label_top_incidence, 2, 0, 1, 1)
        self.slider_incidence = QtWidgets.QSlider(self.widget)
        self.slider_incidence.setOrientation(QtCore.Qt.Vertical)
        self.slider_incidence.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_incidence.setTickInterval(5)
        self.slider_incidence.setObjectName("slider_incidence")
        self.gridLayout.addWidget(self.slider_incidence, 2, 1, 3, 1)
        self.label_middle_incidence = QtWidgets.QLabel(self.widget)
        self.label_middle_incidence.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_middle_incidence.setObjectName("label_middle_incidence")
        self.gridLayout.addWidget(self.label_middle_incidence, 3, 0, 1, 1)
        self.label_bottom_incidence = QtWidgets.QLabel(self.widget)
        self.label_bottom_incidence.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_bottom_incidence.setObjectName("label_bottom_incidence")
        self.gridLayout.addWidget(self.label_bottom_incidence, 4, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.widget)
        self.line = QtWidgets.QFrame(self.gb_incidence)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(self.gb_incidence)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_diffraction = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_diffraction.sizePolicy().hasHeightForWidth())
        self.label_diffraction.setSizePolicy(sizePolicy)
        self.label_diffraction.setObjectName("label_diffraction")
        self.gridLayout_5.addWidget(self.label_diffraction, 0, 0, 1, 2)
        self.sb_incidence_diffraction = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.sb_incidence_diffraction.setObjectName("sb_incidence_diffraction")
        self.gridLayout_5.addWidget(self.sb_incidence_diffraction, 1, 0, 1, 2)
        self.label_top_diffraction = QtWidgets.QLabel(self.widget_2)
        self.label_top_diffraction.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_top_diffraction.setObjectName("label_top_diffraction")
        self.gridLayout_5.addWidget(self.label_top_diffraction, 2, 0, 1, 1)
        self.slider_incidence_diffraction = QtWidgets.QSlider(self.widget_2)
        self.slider_incidence_diffraction.setOrientation(QtCore.Qt.Vertical)
        self.slider_incidence_diffraction.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_incidence_diffraction.setTickInterval(5)
        self.slider_incidence_diffraction.setObjectName("slider_incidence_diffraction")
        self.gridLayout_5.addWidget(self.slider_incidence_diffraction, 2, 1, 3, 1)
        self.label_middle_diffraction = QtWidgets.QLabel(self.widget_2)
        self.label_middle_diffraction.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_middle_diffraction.setObjectName("label_middle_diffraction")
        self.gridLayout_5.addWidget(self.label_middle_diffraction, 3, 0, 1, 1)
        self.label_bottom_diffraction = QtWidgets.QLabel(self.widget_2)
        self.label_bottom_diffraction.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_bottom_diffraction.setObjectName("label_bottom_diffraction")
        self.gridLayout_5.addWidget(self.label_bottom_diffraction, 4, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.gb_incidence)
        self.gb_x_det = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_x_det.sizePolicy().hasHeightForWidth())
        self.gb_x_det.setSizePolicy(sizePolicy)
        self.gb_x_det.setObjectName("gb_x_det")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gb_x_det)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.x_det = QtWidgets.QWidget(self.gb_x_det)
        self.x_det.setEnabled(False)
        self.x_det.setObjectName("x_det")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.x_det)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.slider_incidence_x_det = QtWidgets.QSlider(self.x_det)
        self.slider_incidence_x_det.setOrientation(QtCore.Qt.Vertical)
        self.slider_incidence_x_det.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_incidence_x_det.setTickInterval(5)
        self.slider_incidence_x_det.setObjectName("slider_incidence_x_det")
        self.gridLayout_2.addWidget(self.slider_incidence_x_det, 2, 1, 3, 1)
        self.label = QtWidgets.QLabel(self.x_det)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.label_middle_x_det = QtWidgets.QLabel(self.x_det)
        self.label_middle_x_det.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_middle_x_det.setObjectName("label_middle_x_det")
        self.gridLayout_2.addWidget(self.label_middle_x_det, 3, 0, 1, 1)
        self.sb_incidence_x_det = QtWidgets.QDoubleSpinBox(self.x_det)
        self.sb_incidence_x_det.setObjectName("sb_incidence_x_det")
        self.gridLayout_2.addWidget(self.sb_incidence_x_det, 1, 0, 1, 2)
        self.label_top_x_det = QtWidgets.QLabel(self.x_det)
        self.label_top_x_det.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_top_x_det.setObjectName("label_top_x_det")
        self.gridLayout_2.addWidget(self.label_top_x_det, 2, 0, 1, 1)
        self.label_bottom_x_det = QtWidgets.QLabel(self.x_det)
        self.label_bottom_x_det.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_bottom_x_det.setObjectName("label_bottom_x_det")
        self.gridLayout_2.addWidget(self.label_bottom_x_det, 4, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.x_det)
        self.line_2 = QtWidgets.QFrame(self.gb_x_det)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.y_det = QtWidgets.QWidget(self.gb_x_det)
        self.y_det.setEnabled(False)
        self.y_det.setObjectName("y_det")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.y_det)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.slider_incidence_y_det = QtWidgets.QSlider(self.y_det)
        self.slider_incidence_y_det.setOrientation(QtCore.Qt.Vertical)
        self.slider_incidence_y_det.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_incidence_y_det.setTickInterval(5)
        self.slider_incidence_y_det.setObjectName("slider_incidence_y_det")
        self.gridLayout_3.addWidget(self.slider_incidence_y_det, 2, 1, 3, 1)
        self.label_y_det = QtWidgets.QLabel(self.y_det)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_y_det.sizePolicy().hasHeightForWidth())
        self.label_y_det.setSizePolicy(sizePolicy)
        self.label_y_det.setObjectName("label_y_det")
        self.gridLayout_3.addWidget(self.label_y_det, 0, 0, 1, 2)
        self.label_middle_y_det = QtWidgets.QLabel(self.y_det)
        self.label_middle_y_det.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_middle_y_det.setObjectName("label_middle_y_det")
        self.gridLayout_3.addWidget(self.label_middle_y_det, 3, 0, 1, 1)
        self.sb_incidence_y_det = QtWidgets.QDoubleSpinBox(self.y_det)
        self.sb_incidence_y_det.setObjectName("sb_incidence_y_det")
        self.gridLayout_3.addWidget(self.sb_incidence_y_det, 1, 0, 1, 2)
        self.label_top_y_det = QtWidgets.QLabel(self.y_det)
        self.label_top_y_det.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_top_y_det.setObjectName("label_top_y_det")
        self.gridLayout_3.addWidget(self.label_top_y_det, 2, 0, 1, 1)
        self.label_bottom_y_det = QtWidgets.QLabel(self.y_det)
        self.label_bottom_y_det.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_bottom_y_det.setObjectName("label_bottom_y_det")
        self.gridLayout_3.addWidget(self.label_bottom_y_det, 4, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.y_det)
        self.line_3 = QtWidgets.QFrame(self.gb_x_det)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.z_det = QtWidgets.QWidget(self.gb_x_det)
        self.z_det.setObjectName("z_det")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.z_det)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.slider_incidence_z_det = QtWidgets.QSlider(self.z_det)
        self.slider_incidence_z_det.setOrientation(QtCore.Qt.Vertical)
        self.slider_incidence_z_det.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_incidence_z_det.setTickInterval(5)
        self.slider_incidence_z_det.setObjectName("slider_incidence_z_det")
        self.gridLayout_4.addWidget(self.slider_incidence_z_det, 2, 1, 3, 1)
        self.label_z_det = QtWidgets.QLabel(self.z_det)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_z_det.sizePolicy().hasHeightForWidth())
        self.label_z_det.setSizePolicy(sizePolicy)
        self.label_z_det.setObjectName("label_z_det")
        self.gridLayout_4.addWidget(self.label_z_det, 0, 0, 1, 2)
        self.label_middle_z_det = QtWidgets.QLabel(self.z_det)
        self.label_middle_z_det.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_middle_z_det.setObjectName("label_middle_z_det")
        self.gridLayout_4.addWidget(self.label_middle_z_det, 3, 0, 1, 1)
        self.sb_incidence_z_det = QtWidgets.QDoubleSpinBox(self.z_det)
        self.sb_incidence_z_det.setObjectName("sb_incidence_z_det")
        self.gridLayout_4.addWidget(self.sb_incidence_z_det, 1, 0, 1, 2)
        self.label_top_z_det = QtWidgets.QLabel(self.z_det)
        self.label_top_z_det.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_top_z_det.setObjectName("label_top_z_det")
        self.gridLayout_4.addWidget(self.label_top_z_det, 2, 0, 1, 1)
        self.label_bottom_z_det = QtWidgets.QLabel(self.z_det)
        self.label_bottom_z_det.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_bottom_z_det.setObjectName("label_bottom_z_det")
        self.gridLayout_4.addWidget(self.label_bottom_z_det, 4, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.z_det)
        self.horizontalLayout.addWidget(self.gb_x_det)
        self.gb_incidence_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_incidence_2.sizePolicy().hasHeightForWidth())
        self.gb_incidence_2.setSizePolicy(sizePolicy)
        self.gb_incidence_2.setObjectName("gb_incidence_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gb_incidence_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.gb_incidence_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_incidence_2 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_incidence_2.sizePolicy().hasHeightForWidth())
        self.label_incidence_2.setSizePolicy(sizePolicy)
        self.label_incidence_2.setObjectName("label_incidence_2")
        self.gridLayout_6.addWidget(self.label_incidence_2, 0, 0, 1, 2)
        self.sb_incidence_2 = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.sb_incidence_2.setObjectName("sb_incidence_2")
        self.gridLayout_6.addWidget(self.sb_incidence_2, 1, 0, 1, 2)
        self.label_top_incidence_2 = QtWidgets.QLabel(self.widget_3)
        self.label_top_incidence_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_top_incidence_2.setObjectName("label_top_incidence_2")
        self.gridLayout_6.addWidget(self.label_top_incidence_2, 2, 0, 1, 1)
        self.slider_incidence_2 = QtWidgets.QSlider(self.widget_3)
        self.slider_incidence_2.setOrientation(QtCore.Qt.Vertical)
        self.slider_incidence_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_incidence_2.setTickInterval(5)
        self.slider_incidence_2.setObjectName("slider_incidence_2")
        self.gridLayout_6.addWidget(self.slider_incidence_2, 2, 1, 3, 1)
        self.label_middle_incidence_2 = QtWidgets.QLabel(self.widget_3)
        self.label_middle_incidence_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_middle_incidence_2.setObjectName("label_middle_incidence_2")
        self.gridLayout_6.addWidget(self.label_middle_incidence_2, 3, 0, 1, 1)
        self.label_bottom_incidence_2 = QtWidgets.QLabel(self.widget_3)
        self.label_bottom_incidence_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_bottom_incidence_2.setObjectName("label_bottom_incidence_2")
        self.gridLayout_6.addWidget(self.label_bottom_incidence_2, 4, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget_3)
        self.line_4 = QtWidgets.QFrame(self.gb_incidence_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.widget_4 = QtWidgets.QWidget(self.gb_incidence_2)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_diffraction_2 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_diffraction_2.sizePolicy().hasHeightForWidth())
        self.label_diffraction_2.setSizePolicy(sizePolicy)
        self.label_diffraction_2.setObjectName("label_diffraction_2")
        self.gridLayout_7.addWidget(self.label_diffraction_2, 0, 0, 1, 2)
        self.sb_incidence_diffraction_2 = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.sb_incidence_diffraction_2.setObjectName("sb_incidence_diffraction_2")
        self.gridLayout_7.addWidget(self.sb_incidence_diffraction_2, 1, 0, 1, 2)
        self.label_top_diffraction_2 = QtWidgets.QLabel(self.widget_4)
        self.label_top_diffraction_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_top_diffraction_2.setObjectName("label_top_diffraction_2")
        self.gridLayout_7.addWidget(self.label_top_diffraction_2, 2, 0, 1, 1)
        self.slider_incidence_diffraction_2 = QtWidgets.QSlider(self.widget_4)
        self.slider_incidence_diffraction_2.setOrientation(QtCore.Qt.Vertical)
        self.slider_incidence_diffraction_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_incidence_diffraction_2.setTickInterval(5)
        self.slider_incidence_diffraction_2.setObjectName("slider_incidence_diffraction_2")
        self.gridLayout_7.addWidget(self.slider_incidence_diffraction_2, 2, 1, 3, 1)
        self.label_middle_diffraction_2 = QtWidgets.QLabel(self.widget_4)
        self.label_middle_diffraction_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_middle_diffraction_2.setObjectName("label_middle_diffraction_2")
        self.gridLayout_7.addWidget(self.label_middle_diffraction_2, 3, 0, 1, 1)
        self.label_bottom_diffraction_2 = QtWidgets.QLabel(self.widget_4)
        self.label_bottom_diffraction_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_bottom_diffraction_2.setObjectName("label_bottom_diffraction_2")
        self.gridLayout_7.addWidget(self.label_bottom_diffraction_2, 4, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.gb_incidence_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = GraphicsLayoutWidget(self.dockWidgetContents)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gb_incidence.setTitle(_translate("MainWindow", "Sample"))
        self.label_incidence.setText(_translate("MainWindow", "<html><head/><body><p>Incidence<br/>angle [<span style=\" font-weight:600;\">°</span>]</p></body></html>"))
        self.label_top_incidence.setText(_translate("MainWindow", "30"))
        self.label_middle_incidence.setText(_translate("MainWindow", "15"))
        self.label_bottom_incidence.setText(_translate("MainWindow", "0"))
        self.label_diffraction.setText(_translate("MainWindow", "<html><head/><body><p>Diffraction<br/>angle [<span style=\" font-weight:600;\">°</span>]</p></body></html>"))
        self.label_top_diffraction.setText(_translate("MainWindow", "80"))
        self.label_middle_diffraction.setText(_translate("MainWindow", "40"))
        self.label_bottom_diffraction.setText(_translate("MainWindow", "0"))
        self.gb_x_det.setTitle(_translate("MainWindow", "Detector"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Position<br/>-x [mm]</p></body></html>"))
        self.label_middle_x_det.setText(_translate("MainWindow", "50"))
        self.label_top_x_det.setText(_translate("MainWindow", "99"))
        self.label_bottom_x_det.setText(_translate("MainWindow", "0"))
        self.label_y_det.setText(_translate("MainWindow", "<html><head/><body><p>Position<br/>-y [mm]</p></body></html>"))
        self.label_middle_y_det.setText(_translate("MainWindow", "50"))
        self.label_top_y_det.setText(_translate("MainWindow", "99"))
        self.label_bottom_y_det.setText(_translate("MainWindow", "0"))
        self.label_z_det.setText(_translate("MainWindow", "<html><head/><body><p>Position<br/>-z [mm]</p></body></html>"))
        self.label_middle_z_det.setText(_translate("MainWindow", "50"))
        self.label_top_z_det.setText(_translate("MainWindow", "99"))
        self.label_bottom_z_det.setText(_translate("MainWindow", "0"))
        self.gb_incidence_2.setTitle(_translate("MainWindow", "Beam"))
        self.label_incidence_2.setText(_translate("MainWindow", "<html><head/><body><p>Divergence<br/>radial [mrad]</p></body></html>"))
        self.label_top_incidence_2.setText(_translate("MainWindow", "30"))
        self.label_middle_incidence_2.setText(_translate("MainWindow", "15"))
        self.label_bottom_incidence_2.setText(_translate("MainWindow", "0"))
        self.label_diffraction_2.setText(_translate("MainWindow", "<html><head/><body><p>Diameter<br/>[μm]</p></body></html>"))
        self.label_top_diffraction_2.setText(_translate("MainWindow", "80"))
        self.label_middle_diffraction_2.setText(_translate("MainWindow", "40"))
        self.label_bottom_diffraction_2.setText(_translate("MainWindow", "0"))
from pyqtgraph import GraphicsLayoutWidget
